### ISSUE TITLE
2 PIs showing when there should be 1

### ISSUE THREAD

**Issue by evmadden** [evmadden/SDCexp1#69]
@lancehilliard commit  fba56304b1b754057295a412f0bdf9c400f9eff5  changes the order that the researcher emails is presented in (be very proud) so that mine always comes last.  I noticed when I was testing this that Scott is still showing up on the BSC.Short informed consent but he is not listed in that config for me to remove him.  Not sure where to go to fix it.  Thoughts?

**Comment by lancehilliard** [comment]
@evmadden Mea culpa. I can explain the technical in a call, but I was wrong to invite you to use the literal appsettings.json file to specify researchers or investigators. bd7c6ba5632975005d1f75f3e54b2c61c1503181 removes these values from only that file, such that they each remain defined in the environment-specific configuration files, and that has fixed the problem for me locally.

Assigning to you for review.

**Comment by evmadden** [comment]
Confirming this has worked!  Thanks for taking care of this.  :)  Closing with this comment.
