### ISSUE TITLE
More text flexibility

### ISSUE THREAD

**Issue by evmadden** [evmadden/SDCexp1#71]
With the new verbal branch added, some flexibility is needed in what text is presented on certain pages (like we have done with which researchers are listed and which debrief text gets shown at the very end.  For example, the home page currently tells the participant that they will be shown a series of images and their job is to remember the object in the red box.  This needs to change so that when we are in the Verbal versions of the application, it tells them that they will be shown a series of sentences and will need to pay attention to the underlined word.  Pages that it affects:

- Home page (Home -> Index.cshtml)
- EncodingInstructions.cshtml
- TestInstructions.cshtml
- Welcome.cshtml & WelcomeBack.cshtml (Test)

Part 2 of the question:  We are changing the language to tell them that they are going to be presented with sentences.  Do we think it is a problem that we have an "Image check screen" or that it says "images loading" or, when a problem occurs, "please explain why the images were obscured"?  I only see a slight problem with the 3rd scenario resulting from removing the browser from full-screen.

**Comment by lancehilliard** [comment]
@evmadden fc677f777770cf6499dfe85c0f24f62fbf306a00 changes a lot of files, but I think it addresses these concerns pretty well. Please review and provide feedback, considering the following:

`DebriefHtml` already exists in appsettings.Verbal.Development.json, so feel free to set that to whatever you like to address any "verbal debrief" concern. The software's existing flexibility might be sufficient there.

Regarding the other text presentation concerns, I think I have created a suitable solution by adding four new settings to every configuration.

( hopefully I chose good names and correct jargon below, and hopefully the descriptions make sense -- happy to adjust based on your feedback )

| Setting | Examples | Description |
| --------|----------- | ------------- |
| `StimuliTypeName` | sentence<br>-or-<br>image | the _type of stimuli_ used in the experiment -- describes how the target and context are logically presented to the participant |
| `TargetTypeName` | word<br>-or-<br>object | describes the _type of target_ presented within the given stimuli |
| `TargetDecorationFormat` | underlined&nbsp;{word}<br>-or-<br>{object}&nbsp;in&nbsp;the&nbsp;red&nbsp;box | builds on `TargetTypeName` to also describe the _target decoration_ used to focus the participant's attention within the stimuli |
| `ContextTypeName` | sentence<br>-or-<br>scene | the _context in which the target appears_ - the target's "background" within each stimulus |

( while the examples above are all singular, you'll notice that, in the various appsettings files, each and every of these values specifies both singular _and_ plural forms - _both are required_ )

In all appsettings files except Verbal.Development, I have placed _image_-appropriate values. In the Verbal.Development appsettings file, I have placed _sentence_-appropriate values. Pull and look at the appsettings files, and please execute the web application once per distinct configuration (e.g. once with Verbal.Development and once with, say, _Development_) and observe the difference.

Ideally, you would lay eyeballs on every single change that I made, and verify it for correctness. It was kind of tricky getting the language right with the various lexical landscapes, but I'm pretty satisfied with what I've come up with (again: happy to hear feedback).

Our hopping on a call together might make it easier to _critically_ review the _many_ code locations and user experience scenarios which were impacted by this change. By helping you walk through the code changes themselves, discussing both possible scenarios per each code change, I could probably help you establish logical confidence one way or the other, without you having to run the actual application and work your way to all of the scenarios/permutations of all of the modified screens. Or maybe you're comfortable doing all of that on your own. It's whatever.

Take a look and let me know what you think. Assigning to you for feedback.

**Comment by evmadden** [comment]
Thanks for getting this finished so quickly!  I can confirm that this provides the flexibility needed to change the image/word language where relevant.  Text looks correct in both verbal and visual configurations.  Closing issue with this comment.
