### ISSUE TITLE
incorrect stimuli and target counts

### ISSUE THREAD

**Issue by lancehilliard** [evmadden/SDCexp1#72]
The web application has so far advertised hard-coded (and typically correct) stimuli and target image counts, not derived from the application configuration. This creates an opportunity for varying configurations to inform a user experience which presents misinformation to the participant.

Correct the counts shown to the participant such that they reflect the application configuration, and, so, the user experience that the participant will have.

**Comment by lancehilliard** [comment]
@evmadden, 7a5354c75066d7488f681c2d01d8b1a0d0908440 addresses this issue. Assigning to you - please review and provide feedback.

**Comment by evmadden** [comment]
Tested that the numbers displayed matched the configuration and all looks good!  Leaving it to you @lancehilliard to decide if we should close this issue now.
